### ISSUE TITLE
Agregar Celuzador

### ISSUE THREAD

**Issue by Theblood** [SebaG20xx/DoxxBotCL-Discord#2]
Celuzador es capaz de traer el nombre y la foto de perfil de whatsapp como tambien el estado del mismo

dejo un repositorio con codigo en python3 que consume una api:
https://github.com/Theblood/Celuzador

Tambien dejo un sitio que esta abierto a consultas:
https://celuzador.online/

**Comment by SebaG20xx** [comment]
Acabo de ver el código, mañana yo creo que estaré agregándole el Celuzador

**Comment by SebaG20xx** [comment]
Se agregó el Celuzador en la ultima release
